services:
  spring:
    image: 'springboot/boilerplate:0.0.1'
    build:
      context: '.'
    ports:
      - '8081:8080'
    environment:
      - 'SPRING_PROFILES_ACTIVE=local'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase'  # Postgres에 연결
      - 'SPRING_DATASOURCE_USERNAME=myuser'
      - 'SPRING_DATASOURCE_PASSWORD=secret'
      - 'TZ=Asia/Seoul'
    depends_on:
      - postgres
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
      - 'TZ=Asia/Seoul'
    ports:
      - '5430:5432'

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command:
      - start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak # 데이터베이스 이름
      KC_DB_USERNAME: myuser # DB 사용자 이름
      KC_DB_PASSWORD: secret # DB 비밀번호
      KEYCLOAK_ADMIN: admin # Keycloak 관리자 계정 사용자 이름
      KEYCLOAK_ADMIN_PASSWORD: admin # Keycloak 관리자 계정 비밀번호
    ports:
      - 8082:8080
    depends_on:
      - postgres
