spring:
  config:
    import: optional:application-secret.yml
  docker:
    compose:
      enabled: false
      lifecycle-management:
        readiness-checks-enabled: false
  application:
    name: api
  profiles:
    active: local
  doc:
    api-docs:
      path: /v1/api-docs
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:test;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=60s

jwt:
  secret: my-very-secure-and-strong-key-for-jwt-authentication

api:
  userdetails:
    implementation: counselorUserDetailsService
