spring:
  docker:
    compose:
      enabled: false
      lifecycle-management:
        readiness-checks-enabled: false
  application:
    name: api
  profiles:
    active: local
  doc:
    api-docs:
      path: /v1/api-docs
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5433/caring_note
    driver-class-name: org.postgresql.Driver
    username: cnAdmin
    password: caringNote2024!!
  h2:
    console:
      enabled: true

jwt:
  secret: my-very-secure-and-strong-key-for-jwt-authentication

api:
  userdetails:
    implementation: counselorUserDetailsService
