INSERT INTO counselors (
    id,
    apple_sso_id,
    counseled_counselee_count,
    email,
    google_sso_id,
    medication_counseling_count,
    name,
    participation_days,
    phone_number,
    profile_image_url,
    registration_date,
    status,
    created_date,
    updated_date,
    role_type,
    password
) VALUES (
             'TEST-COUNSELOR-01',
             'apple-sso-id-001',
             10,
             'counselor1@example.com',
             'google-sso-id-001',
             20,
             'John Doe',
             30,
             '01012345678',
             'https://example.com/images/profile1.jpg',
             '2024-12-01',
             'ACTIVE',
             '2024-12-01',
             '2024-12-02',
             'ROLE_ADMIN',
             'securepassword123'
         );


INSERT INTO counselors (
    id,
    apple_sso_id,
    counseled_counselee_count,
    email,
    google_sso_id,
    medication_counseling_count,
    name,
    participation_days,
    phone_number,
    profile_image_url,
    registration_date,
    status,
    created_date,
    updated_date,
    role_type,
    password
) VALUES (
             'TEST-COUNSELOR-02',
             'apple-sso-id-002',
             10,
             'counselor2@example.com',
             'google-sso-id-002',
             20,
             'John Doe',
             30,
             '01012345679',
             'https://example.com/images/profile1.jpg',
             '2024-12-01',
             'ACTIVE',
             '2024-12-01',
             '2024-12-02',
             'ROLE_USER',
             'securepassword123'
         );