name: CI/CD Pipeline (Staging)

on:
  push:
    branches:
      - staging # staging 브랜치만 트리거

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 소스 코드 체크아웃
        uses: actions/checkout@v3

      - name: Docker Buildx 설정
        uses: docker/setup-buildx-action@v2

      - name: Docker Hub 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker 이미지 빌드 및 푸시
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/caring-note-api:${{ github.sha }} # staging 태그 대신 github.sha 사용
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: VM에 배포 (Staging)
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.VM_PORT }}
          script: |
            # staging 디플로이먼트를 대상으로 변경하고 github.sha 태그 사용
            kubectl set image deployment/caring-note-api-staging caring-note-api=${{ secrets.DOCKERHUB_USERNAME }}/caring-note-api:${{ github.sha }} --record -n caring-note-staging